version: '3.9'
services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: koplamp15
      MYSQL_DATABASE: s3-individualproject
  
  backend:
    build: ./S3Project-FindYourTravelBuddy
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/s3-individualproject?createDatabaseIfNotExist=true