version: '3.4'

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ AMQP port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
